[GOVCMS-6928] Ban outgoing HTTP requests in theme
govCMS/scaffold-tooling pull request #271
Opened 2023-08-11 23:26 UTC by barbun

#  Issue
Currently, outgoing HTTP requests can be made utilising either `Drupal::httpClient()` or `GuzzleHttp\Client`. These methods introduce security risks and should be banned.

# Proposed solution
Expand on `phpstan` ruleset (used by `shipshape`) to disallow `GuzzleHttp\Client` namespace and `Drupal::httpClient()` static method.

2023-11-28 00:51 UTC, steveworley requested changes
Two things for this one:

- Rebase against `10.x-develop` to make sure we have the right base
- Create a `phpstan.neon` and update the `shipshape.yml` file to run another sniff with a different configuration, the second configuration will have a lower severity and will be treated as an introduction to get end users time to review the pipeline outputs and update the code as required

Thanks!

2023-12-04 06:30 UTC, barbun commented
thanks @steveworley , pushed an update that adds `phpstan-extra.neon` config file to separate the checks with lower severity.

2023-12-04 06:40 UTC, simesy commented
What is the security risk out of interest, and how would it differ to using Feeds?

2023-12-04 06:57 UTC, barbun commented
> What is the security risk out of interest, and how would it differ to using Feeds?

Thanks @simesy 

The rationale is that a theme should not be making outgoing HTTP requests.

Using Migrate would adhere to Drupal safeguards and also limit data parsing abilities to avoid e.g. malicious executables from being intentionally or unintentionally pulled from a remote at runtime.

2023-12-05 01:08 UTC, simesy commented
> The rationale is that a theme should not be making outgoing HTTP requests.

Welcome to GovCMS lets do weird stuff in the theme!

2023-12-05 01:29 UTC, simesy commented
I don't have any skin in this game but it seems like a sane/safe thing to do as long as no existing SaaS sites are using this method.

2023-12-05 01:33 UTC, barbun commented
> I don't have any skin in this game but it seems like a sane/safe thing to do as long as no existing SaaS sites are using this method.

Good pick up :-) 
Yeah, we are setting severity to low for now, which shouldn't block deployments. I am also doing some testing with the SaaS projects before we merge this.

2024-04-24 04:27 UTC, steveworley approved these changes

2024-04-24 04:29 UTC, steveworley approved these changes

2024-04-24 04:29 UTC, steveworley commented on drupal/settings/all.settings.php
> +$config['swiftmailer.transport']['sendmail_mode'] = 't';
```suggestion
```

2024-04-24 04:30 UTC, merged

2024-07-14 21:51 UTC, murraywoodman commented
There is at least one very large GovCMS clients with skin in the game on this one. In many cases Migrate is not a suitable option for data import, and in these cases running a GET request to pull the data is the only way to get the data in. If this avenue is removed, important functionality will break. This is therefore not a trivial proposal. The security threat should be better explained and clients who are relying on this should be notified. Alternative options for import should be provided.